user/urls.py
from django.urls import path

from .views import *
from .views import my_page, login

app_name = 'user'

urlpatterns = [
    # login.py
    path('', login.user, name='user'),
    path('login', login.LoginView.as_view(), name='login'),
    path('logout', login.logout, name='logout'),
    path('join', login.JoinView.as_view(), name='join'),
    path('kakaoLogin', login.KakaoSignInView.as_view(), name='KakaoSignInView'),
    path('accounts/signin/kakao/callback', login.KaKaoSignInCallBackView.as_view(), name='KaKaoSignInCallBackView'),

    # my_page.py
    path('my_page', my_page.MyPageView.as_view(), name='my_page'),
    path('trading_switch', my_page.trading_switch, name='trading_switch'),

]

user/models.py
from django.db import models


# Create your models here.

class UserModel(models.Model):
    nick_name = models.CharField(max_length=16, unique=True, verbose_name="닉네임")
    kakao_key = models.TextField(default='', verbose_name="카카오 키")
    upbit_access_key = models.TextField(default='', verbose_name="업비트 엑세스 키")
    upbit_secret_key = models.TextField(default='', verbose_name="업비트 시크릿 키")
    email = models.EmailField(null=True, blank=True, verbose_name='이메일')
    # 유저 상태 - 1 : 정상, 0 : 정지, 2~9 : 등급, 77 : 탈퇴
    user_status = models.CharField(max_length=3, default='1', verbose_name='유저 상태')
    safe_trading_status = models.CharField(max_length=3, default='0', verbose_name='안전 매매 활성화 상태')
    dangerous_coin_possession = models.BooleanField(default=False)
    dangerous_trading_status = models.CharField(max_length=3, default='0', verbose_name='위험 매매 활성화 상태')
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name="생성 날짜")


    class Meta:
        verbose_name = "유저 정보"
        db_table = 'user'

user/views.py
import json

import bcrypt
import requests
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from rest_framework import status, generics
from rest_framework.decorators import api_view
from drf_yasg.utils import swagger_auto_schema
from drf_yasg.openapi import Parameter, IN_HEADER, TYPE_STRING
import upbit
from json_response import json_success, json_error
from config.settings.deploy import *
from user.models import UserModel
from user.serializer import UserModelSerializer
import time
import pyupbit
import datetime
from config import *


def user(request):
    return render(request, 'index.html')


class LoginView(generics.ListCreateAPIView):
    """
    로그인
    /user/Login
    """

    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')

    @swagger_auto_schema(operation_summary="로그인 POST", operation_description="dddd", request_body=UserModelSerializer,
                         manual_parameters=swagger_headers)
    def post(self, request, *args, **kwargs):

        # en_kakao_key = encrypt(request.data['kakao'], randomTxt)
        # request.data.update(kakao_key=en_kakao_key)

        return JsonResponse(json_success("S0004", {"CODE": "succes1111"}), status=status.HTTP_200_OK)


def logout(request):
    """
    로그아웃
    /user/logout
    """
    request.session.clear()

    return redirect('/')


class JoinView(generics.ListCreateAPIView):
    """
    회원가입 [GET, POST]

    ---

    """

    def get(self, request, *args, **kwargs):
        """
        회원가입 [GET]

        ---
        회원가입 페이지(Djnago Template Return)
        """
        return render(request, 'join.html')

    def post(self, request, *args, **kwargs):
        """
        회원가입 [POST]
        ---
        # 내용
            - ㅇㅇㅇ : 111
            - ㄴㄴㄴ : 222
            - ㅋㅋㅋ : 333
        # ddd
            - aaaa : 234234
        """

        serializer = UserModelSerializer(data=request.data)

        if serializer.is_valid(raise_exception=True):
            serializer.save()
            request.session['kakao_id'] = request.data['kakao_key']
            return JsonResponse(json_success("S0004", {"CODE": "succes0001"}), status=status.HTTP_200_OK)
        else:
            return JsonResponse(json_error("E0003"), status=status.HTTP_200_OK)


"""
카카오 로그인
/user/kakaoLogin
"""


class KakaoSignInView(generics.ListCreateAPIView):
    def get(self, request):
        app_key = kakao_api_key
        redirect_uri = 'http://localhost:8000/user/accounts/signin/kakao/callback'      #한경 변수 분리 필요
        kakao_auth_api = 'https://kauth.kakao.com/oauth/authorize?response_type=code'

        return redirect(
            f'{kakao_auth_api}&client_id={app_key}&redirect_uri={redirect_uri}'
        )


class KaKaoSignInCallBackView(generics.ListCreateAPIView):
    def get(self, request):
        auth_code = request.GET.get('code')
        kakao_token_api = 'https://kauth.kakao.com/oauth/token'
        data = {
            'grant_type': 'authorization_code',
            'client_id': kakao_api_key,
            'redirection_uri': 'http://localhost:8000/user/accounts/signin/kakao/callback',     #환경 변수 분리 필요
            'code': auth_code
        }

        token_response = requests.post(kakao_token_api, data=data)

        access_token = token_response.json().get('access_token')

        user_info_response = requests.get('https://kapi.kakao.com/v2/user/me',
                                          headers={"Authorization": f'Bearer ${access_token}'})

        user_info_json = user_info_response.json()

        # """암호화"""
        # enc_kakao_key = bcrypt.hashpw(request.session['kakao_id'].encode('utf-8'), bcrypt.gensalt())
        # #회원인 경우 로그인 처리
        # if UserModel.objects.filter(kakao_key = enc_kakao_key).exists():
        #     request.session['kakao_id'] = enc_kakao_key
        #     return redirect(reverse("mainapp:main"))
        # #회원이 아닌 경우 회원가입 페이지로 넘김
        # else:
        #     request.session['enc_kakao_id'] = enc_kakao_key
        #     print(request.session['enc_kakao_id'])
        #     return redirect(reverse("user:join"))

        kakao_key = user_info_json['id']
        # 회원인 경우 로그인 처리
        if UserModel.objects.filter(kakao_key=kakao_key).exists():
            request.session['kakao_id'] = kakao_key
            request.session['nick_name'] = UserModel.objects.get(kakao_key=kakao_key).nick_name
            return redirect(reverse("mainapp:main"))
        # 회원이 아닌 경우 회원가입 페이지로 넘김
        else:
            request.session['enc_kakao_id'] = kakao_key
            return redirect(reverse("user:join"))

        return redirect(reverse("mainapp:main"))


class MyPageView(generics.ListCreateAPIView):
    """
    마이 페이지
    ---
     [GET] : 마이 페이지 조회
    """

    @api_view(['GET'])
    def get(self, request, *args, **kwargs):
        """
        마이 페이지
        ---
         [GET] : 마이 페이지 조회
        """
        if UserModel.objects.get(kakao_key=request.session['kakao_id']):

            user_model = UserModel.objects.get(kakao_key=request.session['kakao_id'])
            model = {'auto_trading_status': user_model.auto_trading_status}

            return render(request, 'my_page.html', model)

        else:
            return render(request, 'login.html')

user/views/login.py
import json

import bcrypt
import requests
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from rest_framework import status, generics
from rest_framework.decorators import api_view
from drf_yasg.utils import swagger_auto_schema
from drf_yasg.openapi import Parameter, IN_HEADER, TYPE_STRING
import upbit
from json_response import json_success, json_error
from config.settings.deploy import *
from user.models import UserModel
from user.serializer import UserModelSerializer
import time
import pyupbit
import datetime
from config import *


def user(request):
    return render(request, 'index.html')


class LoginView(generics.ListCreateAPIView):
    """
    로그인
    /user/Login
    """

    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')

    # @swagger_auto_schema(operation_summary="로그인 POST", operation_description="dddd", request_body=UserModelSerializer,
    #                      manual_parameters=swagger_headers)
    def post(self, request, *args, **kwargs):
        # en_kakao_key = encrypt(request.data['kakao'], randomTxt)
        # request.data.update(kakao_key=en_kakao_key)

        return JsonResponse(json_success("S0004", {"CODE": "succes1111"}), status=status.HTTP_200_OK)


def logout(request):
    """
    로그아웃
    /user/logout
    """
    request.session.clear()

    return redirect('/')


class JoinView(generics.ListCreateAPIView):
    """
    회원가입 [GET, POST]

    ---

    """

    def get(self, request, *args, **kwargs):
        """
        회원가입 [GET]

        ---
        회원가입 페이지(Djnago Template Return)
        """
        return render(request, 'join.html')

    def post(self, request, *args, **kwargs):
        """
        회원가입 [POST]
        ---
        # 내용
            - ㅇㅇㅇ : 111
            - ㄴㄴㄴ : 222
            - ㅋㅋㅋ : 333
        # ddd
            - aaaa : 234234
        """

        serializer = UserModelSerializer(data=request.data)

        if serializer.is_valid(raise_exception=True):
            serializer.save()
            request.session['kakao_id'] = request.data['kakao_key']
            return JsonResponse(json_success("S0004", {"CODE": "succes0001"}), status=status.HTTP_200_OK)
        else:
            return JsonResponse(json_error("E0003"), status=status.HTTP_200_OK)


"""
카카오 로그인
/user/kakaoLogin
"""


class KakaoSignInView(generics.ListCreateAPIView):
    def get(self, request):
        app_key = kakao_api_key
        redirect_uri = 'http://localhost:8000/user/accounts/signin/kakao/callback'  # 환경 변수 분리 필요
        kakao_auth_api = 'https://kauth.kakao.com/oauth/authorize?response_type=code'

        return redirect(
            f'{kakao_auth_api}&client_id={app_key}&redirect_uri={redirect_uri}'
        )


class KaKaoSignInCallBackView(generics.ListCreateAPIView):
    def get(self, request):
        auth_code = request.GET.get('code')
        kakao_token_api = 'https://kauth.kakao.com/oauth/token'
        data = {
            'grant_type': 'authorization_code',
            'client_id': kakao_api_key,
            'redirection_uri': 'http://localhost:8000/user/accounts/signin/kakao/callback',  # 환경 변수 분리 필요
            'code': auth_code
        }

        token_response = requests.post(kakao_token_api, data=data)

        access_token = token_response.json().get('access_token')

        user_info_response = requests.get('https://kapi.kakao.com/v2/user/me',
                                          headers={"Authorization": f'Bearer ${access_token}'})

        user_info_json = user_info_response.json()

        # """암호화"""
        # enc_kakao_key = bcrypt.hashpw(request.session['kakao_id'].encode('utf-8'), bcrypt.gensalt())
        # #회원인 경우 로그인 처리
        # if UserModel.objects.filter(kakao_key = enc_kakao_key).exists():
        #     request.session['kakao_id'] = enc_kakao_key
        #     return redirect(reverse("mainapp:main"))
        # #회원이 아닌 경우 회원가입 페이지로 넘김
        # else:
        #     request.session['enc_kakao_id'] = enc_kakao_key
        #     print(request.session['enc_kakao_id'])
        #     return redirect(reverse("user:join"))

        kakao_key = user_info_json['id']
        # 회원인 경우 로그인 처리
        if UserModel.objects.filter(kakao_key=kakao_key).exists():
            request.session['kakao_id'] = kakao_key
            request.session['nick_name'] = UserModel.objects.get(kakao_key=kakao_key).nick_name
            return redirect(reverse("mainapp:main"))
        # 회원이 아닌 경우 회원가입 페이지로 넘김
        else:
            request.session['enc_kakao_id'] = kakao_key
            return redirect(reverse("user:join"))

        return redirect(reverse("mainapp:main"))


class MyPageView(generics.ListCreateAPIView):
    """
    마이 페이지
    ---
     [GET] : 마이 페이지 조회
    """

    @api_view(['GET'])
    def get(self, request, *args, **kwargs):
        """
        마이 페이지
        ---
         [GET] : 마이 페이지 조회
        """
        if UserModel.objects.get(kakao_key=request.session['kakao_id']):

            user_model = UserModel.objects.get(kakao_key=request.session['kakao_id'])
            model = {'auto_trading_status': user_model.auto_trading_status}

            return render(request, 'my_page.html', model)

        else:
            return render(request, 'login.html')

user/views/my_page.py
import json

import bcrypt
import requests
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from rest_framework import status, generics
from rest_framework.decorators import api_view
from drf_yasg.utils import swagger_auto_schema
from drf_yasg.openapi import Parameter, IN_HEADER, TYPE_STRING
import upbit
from json_response import json_success, json_error
from config.settings.deploy import *
from user.models import UserModel
from user.serializer import UserModelSerializer
import time
import pyupbit
import datetime
from config import *


class MyPageView(generics.ListCreateAPIView):
    """
    마이 페이지
    ---
     [GET] : 마이 페이지 조회
    """

    def get(self, request, *args, **kwargs):
        """
        마이 페이지
        ---
         [GET] : 마이 페이지 조회
        """
        if UserModel.objects.get(kakao_key=request.session['kakao_id']):

            user_model = UserModel.objects.get(kakao_key=request.session['kakao_id'])
            model = {'safe_trading_status': user_model.safe_trading_status}

            return render(request, 'my_page.html', model)

        else:
            return render(request, 'login.html')


@api_view(["PUT"])
def trading_switch(request):
    """
    자동 매매 설정
    /user/trading_switch
    """
    try:
        user_model = UserModel.objects.filter(kakao_key=request.session['kakao_id'])
        if request.data['status'] == '0':
            user_model.update(safe_trading_status='1')

            return JsonResponse(json_success("S0004", {"CODE": "success1001"}), status=status.HTTP_200_OK)
        else:

            user_model.update(safe_trading_status='0')
            return JsonResponse(json_success("S0004", {"CODE": "success1002"}), status=status.HTTP_200_OK)

    except Exception:
        return JsonResponse(json_success("S0004", {"CODE": "error4001"}), status=status.HTTP_200_OK)

user/templates/join.html
<html lang="ko">
{% include "head.html" %}
<body class="join_body">
<div class="container">
    <div class="input-form-backgroud row">
        <div class="input-form col-md-12 mx-auto"><h4 class="mb-3">UAT 회원가입</h4>
            <form class="validation-form" novalidate>
                <div class="row">
                    <div class="col-md-6 mb-3"><label for="nickname">닉네임</label>
                        <input type="text" class="form-control" id="nickname" placeholder="" value="" required
                               maxlength="8">
                        <div class="invalid-feedback"> 닉네임을 입력해주세요.</div>
                    </div>
                </div>
                <div class="mb-3"><label for="email">이메일</label>
                    <input type="email" class="form-control" id="email" placeholder="you@example.com" required>

                    <div class="invalid-feedback"> 이메일을 입력해주세요.</div>
                </div>
                {{ enc_kakao_id }}

                <hr class="mb-4">
                <div class="custom-control custom-checkbox"><input type="checkbox" class="custom-control-input"
                                                                   id="aggrement" required> <label
                        class="custom-control-label" for="aggrement">개인정보 수집 및 이용에 동의합니다.</label></div>
                <div class="mb-4"></div>
                <button class="btn btn-primary btn-lg btn-block" id="joinButton" type="button">가입 완료</button>
            </form>
        </div>
    </div>
    <input type="hidden" id = "kakao" value="{{ request.session.enc_kakao_id }}">
</div>

</body>
</html>
<script>
    var regEmail = /^[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/i;
    $(function () {
        $('#joinButton').click(function () {
            if (!/^([a-zA-Z0-9|가-힣]).{1,8}$/.test($('#nickname').val())) {
                alert("닉네임은 한글, 영문, 숫자만 가능하며 2-8자리 까지 가능 합니다");
                return false;
            }

            if(regEmail.test($('#email').val()) == false){
                alert('이메일 형식이 맞지 않습니다');
                return false;
            }
            if($('#aggrement').is(":checked") == false){
                alert('개인정보 수집 및 이용에 동의 항목이 체크 되어 있지 않습니다');
                return false;
            }
            var send_data = {"nick_name" : $('#nickname').val(),
                                 "kakao_key"     : $('#kakao').val(),
                                 "email"     : $('#email').val()
                }
            $.ajax({

                type: "POST",
                url: "{% url 'user:join' %}",
                data: JSON.stringify(send_data),

                dataType: "json",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("Content-type", "application/json");
                },
                success: function (response) {
                    if (response.data.CODE == "succes0001"){
                        alert("회원가입 완료")
                        window.location.href = '/'
                    } else if (response){
                        console.log(response)

                    }
                },
                error: function (request, status, error) {
                },
            });

        });
    });

</script>

user/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}
{% include "header.html" %}
<body>

    <section id="hero" class="d-flex align-items-center">

        <div class="kakao-login-area" style="margin: 0 auto">
            <a id="custom-login-btn" href="/user/kakaoLogin">
                <img
                        src="//k.kakaocdn.net/14/dn/btroDszwNrM/I6efHub1SN5KCJqLm1Ovx1/o.jpg"
                        width="222"
                        alt="카카오 로그인 버튼"
                />
            </a>
            <hr>
            <a href="/user/kakaoLogin"><div class="join-area" style="text-align: center;">계정이 없으신가요? 가입하기</div></a>
        </div>

    </section>
</body>
</html>

<script>

</script>

user/templates/my_page.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}
{% include "header.html" %}
<body>

<section id="hero" class="d-flex align-items-center">

    {% if "0" == auto_trading_status %}
        <div class="trading_switch-area" style="margin: 0 auto">
            <a href="javascript:void(0)" values="{{ safe_trading_status }}" id="trading_switch" class="btn-about"
               style="background-color: #71c445">안전 매매 시작</a>
        </div>
    {% else %}
        <div class="trading_switch-area" style="margin: 0 auto">
            <a href="javascript:void(0)" values="{{ safe_trading_status }}" id="trading_switch" class="btn-about"
               style="background-color: rgba(225,0,81,0.96)">안전 매매 종료</a>
        </div>
    {% endif %}


</section>
<div class="trading_history" style="padding: 100px">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">코인</th>
            <th scope="col">매수가</th>
            <th scope="col">매매가</th>
            <th scope="col">수익률</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
            <td>@mdo</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
            <td>@fat</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td colspan="2">Larry the Bird</td>
            <td>@twitter</td>
            <td>@twitter</td>
        </tr>
        </tbody>
    </table>
</div>
</body>
</html>

<script>


    $(function () {
        $('#trading_switch').click(function () {
            $.ajax({
                type: "PUT",
                url: "{% url 'user:trading_switch' %}",
                data: JSON.stringify({'status': $('#trading_switch').val()}),

                dataType: "json",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("Content-type", "application/json");
                },
                success: function (response) {
                    if (response.data.CODE == "success1001") {
                        $('#trading_switch').css("background-color", "rgba(225,0,81,0.96)");
                        $('#trading_switch').text('자동매매 종료');
                        $('#trading_switch').val('1')

                    } else if (response.data.CODE == "success1002") {
                        $('#trading_switch').css("background-color", "#71C445FF");
                        $('#trading_switch').text('자동매매 시작');
                        $('#trading_switch').val('0')

                    } else {
                        alert('잠시 후 다시 시도 해주세요');
                        location.reload();
                    }
                },
                error: function (request, status, error) {
                },
            });

        });
    });
</script>