user/urls.py
from django.urls import path

from .views import *
from .views import my_page, login

app_name = 'user'

urlpatterns = [
    # login.py
    path('', login.user, name='user'),
    path('login', login.LoginView.as_view(), name='login'),
    path('logout', login.logout, name='logout'),
    path('join', login.JoinView.as_view(), name='join'),
    path('kakaoLogin', login.KakaoSignInView.as_view(), name='KakaoSignInView'),
    path('accounts/signin/kakao/callback', login.KaKaoSignInCallBackView.as_view(), name='KaKaoSignInCallBackView'),

    # my_page.py
    path('my_page', my_page.MyPageView.as_view(), name='my_page'),
    path('trading_switch', my_page.trading_switch, name='trading_switch'),

]

templates/footer.html
<!-- Vendor JS Files -->
  <script src="/static/vendor/purecounter/purecounter.js"></script>
  <script src="/static/vendor/aos/aos.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="/static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/js/main.js"></script>
<footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Sim Wan Woo</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/ -->
        Designed by <a href="https://bootstrapmade.com/"></a>
      </div>
    </div>
</footer><!-- End  Footer -->

templates/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>uat</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="/static/img/favicon.ico" rel="icon">
    <link href="/static/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/static/vendor/aos/aos.css" rel="stylesheet">
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="/static/css/style.css" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% comment %}KAKAO{% endcomment %}
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>

    {# JQuery #}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</head>

templates/header.html
<header id="header" class="fixed-top">
    <div class="container-fluid d-flex justify-content-between align-items-center">

        <h1 class="logo me-auto me-lg-0"><a href="/">uat</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo"><img src="/static/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
                <li><a id="home" class="itemli " href="/">Home</a></li>
                {#          <li><a id="about" class="itemli " href="/mainapp/about">About</a></li>#}
                {#          <li><a id="resume" class="itemli " href="/mainapp/resume">Resume</a></li>#}
                {#          <li><a id="services" class="itemli " href="/mainapp/services">Services</a></li>#}
                {#          <li><a id="portfolio" class="itemli " href="/mainapp/portfolio">Portfolio</a></li>#}
                {#          <li><a id="contact" class="itemli " href="/mainapp/contact">Contact</a></li>#}

            </ul>

            <i class="bi bi-list mobile-nav-toggle"></i>

        </nav><!-- .navbar -->

        <div class="header-social-links">
            {#        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>#}
            {#        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>#}
            {#        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>#}
            {#        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>#}
        </div>

        {% if request.session.nick_name %}
            <div class="user-area" style="width: 300px; color: #f0f0f0; margin-right: 30px;">
                <span  >닉네임 : {{ request.session.nick_name }}</span>
                <a style="color: #f0f0f0" href="{% url 'user:logout' %}"><span style="float: right">LogOut</span></a>
                <a style="color: #f0f0f0" href="{% url 'user:my_page' %}"><span>마이 페이지</span></a>

            </div>
        {% else %}
            <a href="user/login"><span style="color: #f0f0f0; margin-right: 30px;">로그인</span></a>
        {% endif %}




    </div>

</header><!-- End Header -->

<script>

    var hostname = location.hostname

    var url = window.location.href

    var itemli = document.getElementsByClassName('itemli');

    urlSplit = url.split('/');


    if (urlSplit[4] == 'Home') {
        document.getElementsByClassName('active').className = ""
        document.getElementById('about').className += 'active'

    } else if (urlSplit[4] == 'resume') {
        document.getElementsByClassName('active').className = ""
        document.getElementById('resume').className += 'active'
    } else if (urlSplit[4] == 'services') {
        document.getElementsByClassName('active').className = ""
        document.getElementById('services').className += 'active'
    } else if (urlSplit[4] == 'portfolio') {
        document.getElementsByClassName('active').className = ""
        document.getElementById('portfolio').className += 'active'
    } else if (urlSplit[4] == 'contact') {
        document.getElementsByClassName('active').className = ""
        document.getElementById('contact').className += 'active'
    } else {
        document.getElementsByClassName('active').className = ""
        document.getElementById('home').className += 'active'


    }


</script>